/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ux;

import Kelas.Kategori;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import popup.PopUpTambahKategori;
import static popup.PopUpTambahKategori.lb_Id;
import static popup.PopUpTambahKategori.tf_Kode;
import static popup.PopUpTambahKategori.tf_Nama;

/**
 *
 * @author lenovo
 */
public class kategori extends javax.swing.JPanel implements Kategori.PerubahanData {

    private Kategori ktgr;

    /**
     * Creates new form kategori
     */
    public kategori() throws SQLException {
        initComponents();

        ktgr = new Kategori();
        ktgr.TambahPerubahanData(this);

        loadTabel();
        pn_uploadkeluar.putClientProperty(FlatClientProperties.STYLE, "arc:50");

        FlatLightLaf.setup();

        UIManager.put("Button.arc", 15);
        UIManager.put("Component.arc", 20);
        UIManager.put("CheckBox.arc", 10);
        UIManager.put("Button.background", Color.WHITE);

        pn_Dasar.putClientProperty(FlatClientProperties.STYLE, "arc:75");

    }

    public void loadTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn(null);
        model.addColumn("Kode Kategori Surat");
        model.addColumn("Nama Kategori Surat");

        try {
            Kategori k = new Kategori();
            ResultSet data = k.KodeTampilTabel();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("id_ktgr"),
                    data.getString("kode"),
                    data.getString("nama"),});
            }

            data.close();
        } catch (SQLException sQLException) {
        }

        tb_Kategori.setModel(model);

        tb_Kategori.getColumnModel().getColumn(0).setMinWidth(0);
        tb_Kategori.getColumnModel().getColumn(0).setMaxWidth(0);
        tb_Kategori.getColumnModel().getColumn(0).setWidth(0);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_Dasar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_Kategori = new javax.swing.JTable();
        pn_uploadkeluar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(234, 242, 248));
        setLayout(new java.awt.CardLayout());

        pn_Dasar.setBackground(new java.awt.Color(255, 255, 255));

        tb_Kategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "1", "1", "1"},
                {"2", "2", "2", "2"},
                {"3", "3", "3", "3"},
                {"4", "4", "4", "4"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_Kategori.setRowHeight(30);
        tb_Kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_KategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_Kategori);

        pn_uploadkeluar.setBackground(new java.awt.Color(234, 242, 248));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 125, 197));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Kategori");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Disini !");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/upload_file14.png"))); // NOI18N

        javax.swing.GroupLayout pn_uploadkeluarLayout = new javax.swing.GroupLayout(pn_uploadkeluar);
        pn_uploadkeluar.setLayout(pn_uploadkeluarLayout);
        pn_uploadkeluarLayout.setHorizontalGroup(
            pn_uploadkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_uploadkeluarLayout.createSequentialGroup()
                .addGap(578, 578, 578)
                .addGroup(pn_uploadkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(540, 540, 540))
        );
        pn_uploadkeluarLayout.setVerticalGroup(
            pn_uploadkeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_uploadkeluarLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pn_DasarLayout = new javax.swing.GroupLayout(pn_Dasar);
        pn_Dasar.setLayout(pn_DasarLayout);
        pn_DasarLayout.setHorizontalGroup(
            pn_DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DasarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pn_DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_uploadkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        pn_DasarLayout.setVerticalGroup(
            pn_DasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_DasarLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(pn_uploadkeluar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        add(pn_Dasar, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            PopUpTambahKategori pusm = new PopUpTambahKategori(null, true, ktgr);
            pusm.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tb_KategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_KategoriMouseClicked
        try {
            int baris = tb_Kategori.rowAtPoint(evt.getPoint());
            String id = tb_Kategori.getModel().getValueAt(baris, 0).toString();
            String kode = tb_Kategori.getValueAt(baris, 1).toString();
            String nama = tb_Kategori.getValueAt(baris, 2).toString();

            PopUpTambahKategori popUpKategori = new PopUpTambahKategori(null, true, ktgr);

            lb_Id.setText(id);
            tf_Kode.setText(kode);
            tf_Nama.setText(nama);
            popUpKategori.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(kategori.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_KategoriMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pn_Dasar;
    private javax.swing.JPanel pn_uploadkeluar;
    private javax.swing.JTable tb_Kategori;
    // End of variables declaration//GEN-END:variables
@Override
    public void AktifPerubahanData() {
        loadTabel();
    }

}
